// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBr1aJ-iIQNmKADpiOoff1JA1Exs6Oev64',
    appId: '1:645706286661:web:1ef1bf9af10070a60f052c',
    messagingSenderId: '645706286661',
    projectId: 'scam-daff5',
    authDomain: 'scam-daff5.firebaseapp.com',
    storageBucket: 'scam-daff5.appspot.com',
    measurementId: 'G-84VKQ7XKKG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOzX7F9o2Qj4pzWs9wx0lVA5F2MLVYPmM',
    appId: '1:645706286661:android:ac64e0d9daf4167a0f052c',
    messagingSenderId: '645706286661',
    projectId: 'scam-daff5',
    storageBucket: 'scam-daff5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNBHAz1S5ddqEA5W79Bq12n5HtFJLQIWI',
    appId: '1:645706286661:ios:138622be9611524e0f052c',
    messagingSenderId: '645706286661',
    projectId: 'scam-daff5',
    storageBucket: 'scam-daff5.appspot.com',
    iosBundleId: 'com.example.boltapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNBHAz1S5ddqEA5W79Bq12n5HtFJLQIWI',
    appId: '1:645706286661:ios:24b1de723d57c7fd0f052c',
    messagingSenderId: '645706286661',
    projectId: 'scam-daff5',
    storageBucket: 'scam-daff5.appspot.com',
    iosBundleId: 'com.example.boltapp.RunnerTests',
  );
}
